import Head from "next/head";

import { useState } from "react";
import { useLookup } from "~/hooks/useLookup";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <h1 className="text-2xl font-bold">
            Welcome to LookupLogger
          </h1>
          <SearchBar />
        </div>
      </main>
    </>
  );
}

function SearchBar() {
  const [query, setQuery] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const { data, isLoading, error } = useLookup(submittedQuery);

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if(query === "") {
      return;
    }
    // Perform search
    setSubmittedQuery(query);
  };

  return (
    <div className="p-4">
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          className="border border-gray-300 rounded-lg px-4 py-2 w-full"
          placeholder="Enter your search query..."
        />
        <button
          type="submit"
          className="bg-blue-500 text-white rounded-lg px-4 py-2 mt-2"
        >
          Search
        </button>
      </form>

      {isLoading && <div>Loading...</div>}
      {error && <div>Error fetching data</div>}
      {data && (
        <div className="mt-4">
          <h2 className="font-bold text-lg">Search Results:</h2>
          <ul>
            <pre>
            {JSON.stringify(data.data)}
            </pre>
          </ul>
        </div>
      )}
    </div>
  );
}
